In [1]:
using DifferentialEquations
using Plots

In [2]:
function lorenz!(du,u,p,t)
    x,y,z = u
    σ,ρ,β = p
    
    du[1] = dx = σ*(y-x)
    du[2] = dy = x*(ρ-z) - y
    du[3] = dz = x*y - β*z
end

lorenz! (generic function with 1 method)

In [3]:
u0 = [1.0;0.0;0.0]
tspan = (0.0,1.0)
param=[10.0, 28.0, 8/3]
prob = ODEProblem(lorenz!,u0,tspan,param)
sol=solve(prob)

retcode: Success
Interpolation: Automatic order switching interpolation
t: 28-element Array{Float64,1}:
 0.0
 3.5678604836301404e-5
 0.0003924646531993154
 0.0032624077544510573
 0.009058075635317072
 0.01695646895607931
 0.0276899566248403
 0.041856345938267966
 0.06024040228733675
 0.08368539694547242
 0.11336497050342806
 0.14862178548871152
 0.18703974465019643
 ⋮
 0.37221152547525677
 0.4201372705729432
 0.4637203592547958
 0.5049460289663918
 0.5570622537949965
 0.6068387449874374
 0.6690203938696947
 0.7276640840586802
 0.798854234447563
 0.8763207996400417
 0.9661628933695969
 1.0
u: 28-element Array{Array{Float64,1},1}:
 [1.0, 0.0, 0.0]
 [0.9996434557625105, 0.0009988049817849058, 1.781434788799208e-8]
 [0.9961045497425811, 0.010965399721242457, 2.146955365838907e-6]
 [0.9693591634199452, 0.08977060667778931, 0.0001438018342266937]
 [0.9242043615038835, 0.24228912482984957, 0.0010461623302512404]
 [0.8800455868998046, 0.43873645009348244, 0.0034242593451028745]
 [0.84833098777

In [4]:
u0=sol.u[end]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan,param)
sol=solve(prob)

retcode: Success
Interpolation: Automatic order switching interpolation
t: 1276-element Array{Float64,1}:
   0.0
   0.0643212998173729
   0.12146049375600403
   0.19404894194474215
   0.2741028434949973
   0.3763294534562411
   0.47642405263600096
   0.5862338131757949
   0.6889702298685345
   0.8137510825197651
   0.9188908394845217
   1.0604124384245877
   1.1767908269282734
   ⋮
  99.22024114623642
  99.28138344136775
  99.34996736602218
  99.42505175481546
  99.5169515396852
  99.59466806892196
  99.66916182333932
  99.74301506480711
  99.81291495286696
  99.88460024620092
  99.97127652893508
 100.0
u: 1276-element Array{Array{Float64,1},1}:
 [-9.395403780701917, -9.093416304499454, 28.553652185231734]
 [-8.996304644165681, -8.115195082683018, 28.73842072687945]
 [-8.43238478410594, -7.404436687691967, 28.24645181694211]
 [-7.771691211804133, -7.056393785346572, 27.094715956612436]
 [-7.462783722695311, -7.433832934524049, 25.80792961701246]
 [-7.8842781272262386, -8.68183492781534

In [5]:
plotly()

┌ Info: For saving to png with the Plotly backend ORCA has to be installed.
└ @ Plots /Users/michael/.julia/packages/Plots/cc8wh/src/backends.jl:363


Plots.PlotlyBackend()

In [37]:
plot(sol,vars=(1,2,3),size=(1000,1000))

<!DOCTYPE html>
 
 
 Plots.jl

In [7]:
z=sol[1,:]+randn(size(sol[1,:]))
plot(z)

<!DOCTYPE html>
 
 
 Plots.jl

In [9]:
cd("/Users/michael/work/GitHub/place")

In [498]:
include("Place.jl")

Main.Place

In [499]:
mymodel=Place.buildmodel(z)

Main.Place.PlaceModel(Main.Place.BasisFunc[Main.Place.BasisFunc(Main.Place.gaussian, [0, 1, 2, 3], 14.220366704474614, [1.9448147950399433 -1.8095562172310133 … -10.927233396519032 8.225394934779468; 0.9227748883014358 -2.8893701375484593 … -8.454589172908815 10.369276065522369; -1.7981714577141723 -7.895374287676002 … -7.6502624884058035 11.842437336428066; -4.033999416951307 -15.75181156888904 … -6.1073852432536215 11.139136319390126], Any[]), Main.Place.BasisFunc(Main.Place.tophat, [0, 1, 2, 3], 10.152528876256499, [1.9448147950399433 -1.8095562172310133 … -10.927233396519032 8.225394934779468; 0.9227748883014358 -2.8893701375484593 … -8.454589172908815 10.369276065522369; -1.7981714577141723 -7.895374287676002 … -7.6502624884058035 11.842437336428066; -4.033999416951307 -15.75181156888904 … -6.1073852432536215 11.139136319390126], [1.1331419059201029]), Main.Place.BasisFunc(Main.Place.tophat, [0, 1, 2, 3], 16.971665075643358, [1.9448147950399433 -1.8095562172310133 … -10.9272333965

In [502]:
mymodel.rbf

500-element Array{Main.Place.BasisFunc,1}:
 Main.Place.BasisFunc(Main.Place.gaussian, [0, 1, 2, 3], 14.220366704474614, [1.9448147950399433 -1.8095562172310133 … -10.927233396519032 8.225394934779468; 0.9227748883014358 -2.8893701375484593 … -8.454589172908815 10.369276065522369; -1.7981714577141723 -7.895374287676002 … -7.6502624884058035 11.842437336428066; -4.033999416951307 -15.75181156888904 … -6.1073852432536215 11.139136319390126], Any[])
 Main.Place.BasisFunc(Main.Place.tophat, [0, 1, 2, 3], 10.152528876256499, [1.9448147950399433 -1.8095562172310133 … -10.927233396519032 8.225394934779468; 0.9227748883014358 -2.8893701375484593 … -8.454589172908815 10.369276065522369; -1.7981714577141723 -7.895374287676002 … -7.6502624884058035 11.842437336428066; -4.033999416951307 -15.75181156888904 … -6.1073852432536215 11.139136319390126], [1.1331419059201029])
 Main.Place.BasisFunc(Main.Place.tophat, [0, 1, 2, 3], 16.971665075643358, [1.9448147950399433 -1.8095562172310133 … -10.927233396

In [482]:
xi=[ 1 3 11 12 123 4 14]

1×7 Array{Int64,2}:
 1  3  11  12  123  4  14

In [448]:
	function qrappend(Q,R,x)
		# [Q,R] = qrappend(Q,R,x) append a column to a QR factorization.
		# If [Q,R] = qr(A) is the original QR factorization of A,
		# then [Q,R] = qrappend(Q,R,x) changes Q and R to be the
		# factorization of the matrix obtained by appending an extra
		# column, x, to A.
		# ported from MATLAB code

		if isempty(Q)
  			Q,R = qr(x)
		else
			~,m = size(Q)
			m += 1
			r = Q'*x			 # best fit of x by Q
			R = [R r] 		 # add coeff to R
		  	q= x - Q*r 		 # q is orthogonal part of x
			f= norm(q)
		  	R = [R; zeros(1,m);] # update R for q
  			R[m,m] = f[1] 		 # f is coeff of q when normalized
			Q = [Q q/f] 		 # extend basis by normalized q
		end
		return Q,R
	end

qrappend (generic function with 1 method)

In [432]:
Q1,R1=qrappend(Q,R,x)

MethodError: MethodError: Cannot `convert` an object of type Array{Float64,2} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, !Matched::Unitful.Quantity) where T<:Real at /Users/michael/.julia/packages/Unitful/KE9TK/src/conversion.jl:144
  convert(::Type{T}, !Matched::Unitful.Level) where T<:Real at /Users/michael/.julia/packages/Unitful/KE9TK/src/logarithm.jl:22
  convert(::Type{T}, !Matched::Unitful.Gain) where T<:Real at /Users/michael/.julia/packages/Unitful/KE9TK/src/logarithm.jl:62
  ...

In [433]:
			~,m = size(Q)
			m += 1
			r = Q'*x			 # best fit of x by Q
			R = [R r] 		 # add coeff to R
		  	q= x - Q*r; 		 # q is orthogonal part of x
			f= norm(q);

In [436]:
		  	R = [R; zeros(1,m);] # update R for q


2×2 Array{Float64,2}:
 -17.0035  0.641234
   0.0     0.0

In [441]:
R[m,m] = f[1,1]

17.429156604280404

In [447]:
			Q = [Q q/f] 		 # extend basis by normalized q



300×2 Array{Float64,2}:
 -0.0500145    0.0246114
  0.023056    -0.0407132
  0.0171193    0.0359323
 -0.122163     0.0417078
  0.00923704   0.016312
 -0.0713078    0.041418
 -0.050033    -0.026858
  0.0376097   -0.149806
 -0.00250004  -0.126627
  0.0268241    0.0317266
  0.0687311    0.0605073
 -0.0394387   -0.0944212
 -0.0610161    0.0159982
  ⋮           
  0.0737978   -0.0655148
  0.0550121    0.0275678
  0.110831     0.0107941
  0.00819294   0.000499567
  0.0227277    0.0473315
 -0.0242808    0.0976657
  0.0356201   -0.0408134
  0.0449911   -0.0265367
 -0.101191     0.0334984
  0.0757387   -0.0579845
  0.0143999   -0.0599886
 -0.0507621    0.0926051

In [445]:
q

300×1 Array{Float64,2}:
  0.4289567132000065
 -0.7095965323816504
  0.6262703301637297
  0.7269319888197072
  0.28430428790290735
  0.7218810334854503
 -0.4681123514508467
 -2.6110004210962154
 -2.206993939168474
  0.5529673110533949
  1.0545908542008193
 -1.6456820589993852
  0.27883574425292174
  ⋮
 -1.1418682603928683
  0.48048391003367635
  0.18813203623063707
  0.00870703965734827
  0.8249485933143031
  1.702231147746271
 -0.7113440100032242
 -0.46251207941862477
  0.5838496127510451
 -1.0106214292480828
 -1.045550694207437
  1.6140293933242442

In [490]:
xi

1×7 Array{Int64,2}:
 1  3  11  12  123  4  14

In [491]:
filter(x -> x > 4, xi)

4-element Array{Int64,1}:
  11
  12
 123
  14

In [492]:
xi

1×7 Array{Int64,2}:
 1  3  11  12  123  4  14

In [458]:
mb[1]

5